version: '3.7'

services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    restart: always
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    expose:
      - 9200
      - 9300
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - 'elasticsearch-data:/usr/share/elasticsearch/data'

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.5.1
    restart: always
    environment:
      - elasticsearch.username=kibana
      - elasticsearch.password=password
    ports:
      - 5601:5601

volumes:
  elasticsearch-data:
